### ISSUE TITLE
One word per segment

### ISSUE THREAD

**Issue by bookoly** [CodeWithKyrian/whisper.php#2]
Hey @CodeWithKyrian,

thank you for this awesome package 🫶 .

I tried to get one word per segment working, with these two methods (withMaxLen and withSplitOnWord):

```
    $params = WhisperFullParams::default()
        ->withMaxLen(1)
        ->withSplitOnWord(true)
        ->withNThreads(4)
        ->withLanguage('en');
```

But it doesn't work like described in this [issue](https://github.com/ggerganov/whisper.cpp/issues/49#issuecomment-2196996482). I still get whole sentences. Do you know what I'm doing wrong ?

Thanks in advance,
Alex

**Comment by CodeWithKyrian** [comment]
Hello @bookoly,  

Thank you for the kind words. I’m glad you’re enjoying the package! 🫶  

To achieve token-level timestamps and effectively use `withMaxLen`, you need to explicitly enable token timestamps using `withTokenTimestamps`.  

The example you referred to works because the script automatically sets `token_timestamps` to `true` when `max_len` is greater than zero. However, in Whisper.php, this automation isn’t implemented (yet). I’ve considered adding it for convenience, but for now, you’ll need to set it explicitly. 

```php  
$params = WhisperFullParams::default()
    ->withTokenTimestamps()
    ->withMaxLen(1)
    ->withSplitOnWord(true) // Optional: prevents splitting on tokens
    ->withNThreads(4)
    ->withLanguage('en');
```  

This should give you one word per segment as expected. Let me know if you have any further questions or run into issues.

**Comment by bookoly** [comment]
@CodeWithKyrian Thank you very much. That worked for me 🙂
